# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# Book settings
# -------------
title: Tilastot ja todennäköisyys
author: LUMA-tiimi, Lapin AMK / Minna Korhonen
copyright: "2022"
logo: logo.png

# Execution settings
# -------------------
execute:
  execute_notebooks: force

# GitHub-settings
# ----------------
repository:
  url: https://github.com/luma-lapinamk/minna-tiltod
  branch: master

# HTML-settings
# --------------
html:
  use_issues_button: false
  use_repository_button: true
  extra_navbar: <a href="https://jupyterbook.org">Jupyter Book</a> voimaa
launch_buttons:
  binderhub_url: "https://mybinder.org/"
  thebe: true